export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_CART = 'TOGGLE_CART';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM';
export const ITEM_REMOVE = 'ITEM_REMOVE';